### ISSUE TITLE
installing issue

### ISSUE THREAD

**Issue by eviled23** [orsinium/homoglyphs#5]
Hi, im receiving the following error during the installation

Collecting homoglyphs
  Using cached homoglyphs-1.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Edward\AppData\Local\Temp\pycharm-packaging\homoglyphs\setup.py", line 15, in <module>
        long_description=open('README.rst').read(),
      File "C:\Users\Edward\Desktop\monitorV2_json\venv\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1142: character maps to <undefined>

**Comment by orsinium** [comment]
Oh, yeah, this is Windows installation bug. I will fix it today.

**Comment by orsinium** [comment]
Fixed into new version 1.2.4. Please, install fixed version:

```bash
pip install -U homoglyphs
```

Thank you for homoglyphs usage. Press on star if you like this project :)
