### ISSUE TITLE
Repeat to_ascii -> freeze

### ISSUE THREAD

**Issue by ariutta** [orsinium/homoglyphs#6]
Cool library!

Sadly, I'm running into a bug where `to_ascii` works a few times and then freezes indefinitely. I've tried it using Python3.6 on both macOS and Linux.

To reproduce this bug, you can run the following code:

```py
import homoglyphs as hg
homoglyphs = hg.Homoglyphs(strategy=hg.STRATEGY_LOAD)
for x in range(1, 5):
  print(homoglyphs.to_ascii('a'))
```

It should print `[a]` about 3 times before freezing. It seems that the final time before freezing is noticeably slower than the first couple of times.

**Comment by DeltaF1** [comment]
This is happening on a fresh install of version 1.3.5

```py
>>> homoglyphs = hg.Homoglyphs(languages={'en'}, strategy=hg.STRATEGY_LOAD, ascii_range=range(256),categories=('LATIN', 'COMMON', 'CYRILLIC'))
>>> homoglyphs.to_ascii('prĕparations')

[[ Long time waiting to return here before issuing an interrupt ]]

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".virtualenvs/src-py3/lib/python3.6/site-packages/homoglyphs/core.py", line 241, in to_ascii
    return self.uniq_and_sort(self._to_ascii(text))
  File ".virtualenvs/src-py3/lib/python3.6/site-packages/homoglyphs/core.py", line 173, in uniq_and_sort
    result = list(set(data))
  File ".virtualenvs/src-py3/lib/python3.6/site-packages/homoglyphs/core.py", line 237, in _to_ascii
    if max(map(ord, variant)) in self.ascii_range:
KeyboardInterrupt
```
